module.exports = {
  projects: [
    "<rootDir>/apps/diagram-demo",
    "<rootDir>/libs/check-type",
    "<rootDir>/apps/triangle-api",
    "<rootDir>/apps/form-builder",
    "<rootDir>/libs/triangle",
    "<rootDir>/libs/vector-math",
    "<rootDir>/libs/fedaco",
    "<rootDir>/libs/annotation",
    "<rootDir>/libs/ice-box",
    "<rootDir>/apps/dev-app",
    "<rootDir>/libs/triangle-icons",
    "<rootDir>/apps/runtime-drag",
    "<rootDir>/libs/lofn",
    "<rootDir>/libs/http",
    "<rootDir>/libs/iterator",
    "<rootDir>/libs/runner",
    "<rootDir>/libs/nanofn",
  ],
};
