apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: -
    tier: backend
  name: -
  namespace: nginx-project
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: -
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: -
        tier: backend
    spec:
      volumes:
        - name: env---
          secret:
            secretName: --env
            defaultMode: 420
        - name: volume-data---
          persistentVolumeClaim:
            claimName: 
      containers:
        - name: 
          image: //:-
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: env---
              readOnly: true
              mountPath: /var/www/.env
              subPath: .env
            - name: volume-data---
              readOnly: false
              mountPath: /data
          env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          readinessProbe:
            httpGet:
              path: /api
              port: 80
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: aliyun-registry
