/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license
 */

import { Component } from '@angular/core';


@Component({
  selector: 'tri-demo-icon-twotone',
  template: `
    <tri-icon svgIcon="twotone:account-book"></tri-icon>
    <tri-icon svgIcon="twotone:alert"></tri-icon>
    <tri-icon svgIcon="twotone:api"></tri-icon>
    <tri-icon svgIcon="twotone:appstore"></tri-icon>
    <tri-icon svgIcon="twotone:audio"></tri-icon>
    <tri-icon svgIcon="twotone:bank"></tri-icon>
    <tri-icon svgIcon="twotone:bell"></tri-icon>
    <tri-icon svgIcon="twotone:book"></tri-icon>
    <tri-icon svgIcon="twotone:box-plot"></tri-icon>
    <tri-icon svgIcon="twotone:bug"></tri-icon>
    <tri-icon svgIcon="twotone:build"></tri-icon>
    <tri-icon svgIcon="twotone:bulb"></tri-icon>
    <tri-icon svgIcon="twotone:calculator"></tri-icon>
    <tri-icon svgIcon="twotone:calendar"></tri-icon>
    <tri-icon svgIcon="twotone:camera"></tri-icon>
    <tri-icon svgIcon="twotone:car"></tri-icon>
    <tri-icon svgIcon="twotone:carry-out"></tri-icon>
    <tri-icon svgIcon="twotone:check-circle"></tri-icon>
    <tri-icon svgIcon="twotone:check-square"></tri-icon>
    <tri-icon svgIcon="twotone:ci-circle"></tri-icon>
    <tri-icon svgIcon="twotone:ci"></tri-icon>
    <tri-icon svgIcon="twotone:clock-circle"></tri-icon>
    <tri-icon svgIcon="twotone:close-circle"></tri-icon>
    <tri-icon svgIcon="twotone:close-square"></tri-icon>
    <tri-icon svgIcon="twotone:cloud"></tri-icon>
    <tri-icon svgIcon="twotone:code"></tri-icon>
    <tri-icon svgIcon="twotone:compass"></tri-icon>
    <tri-icon svgIcon="twotone:contacts"></tri-icon>
    <tri-icon svgIcon="twotone:container"></tri-icon>
    <tri-icon svgIcon="twotone:control"></tri-icon>
    <tri-icon svgIcon="twotone:copy"></tri-icon>
    <tri-icon svgIcon="twotone:copyright-circle"></tri-icon>
    <tri-icon svgIcon="twotone:copyright"></tri-icon>
    <tri-icon svgIcon="twotone:credit-card"></tri-icon>
    <tri-icon svgIcon="twotone:crown"></tri-icon>
    <tri-icon svgIcon="twotone:customer-service"></tri-icon>
    <tri-icon svgIcon="twotone:dashboard"></tri-icon>
    <tri-icon svgIcon="twotone:database"></tri-icon>
    <tri-icon svgIcon="twotone:delete"></tri-icon>
    <tri-icon svgIcon="twotone:diff"></tri-icon>
    <tri-icon svgIcon="twotone:dislike"></tri-icon>
    <tri-icon svgIcon="twotone:dollar-circle"></tri-icon>
    <tri-icon svgIcon="twotone:dollar"></tri-icon>
    <tri-icon svgIcon="twotone:down-circle"></tri-icon>
    <tri-icon svgIcon="twotone:down-square"></tri-icon>
    <tri-icon svgIcon="twotone:edit"></tri-icon>
    <tri-icon svgIcon="twotone:environment"></tri-icon>
    <tri-icon svgIcon="twotone:euro-circle"></tri-icon>
    <tri-icon svgIcon="twotone:euro"></tri-icon>
    <tri-icon svgIcon="twotone:exclamation-circle"></tri-icon>
    <tri-icon svgIcon="twotone:experiment"></tri-icon>
    <tri-icon svgIcon="twotone:eye-invisible"></tri-icon>
    <tri-icon svgIcon="twotone:eye"></tri-icon>
    <tri-icon svgIcon="twotone:file-add"></tri-icon>
    <tri-icon svgIcon="twotone:file-excel"></tri-icon>
    <tri-icon svgIcon="twotone:file-exclamation"></tri-icon>
    <tri-icon svgIcon="twotone:file-image"></tri-icon>
    <tri-icon svgIcon="twotone:file-markdown"></tri-icon>
    <tri-icon svgIcon="twotone:file-pdf"></tri-icon>
    <tri-icon svgIcon="twotone:file-ppt"></tri-icon>
    <tri-icon svgIcon="twotone:file-text"></tri-icon>
    <tri-icon svgIcon="twotone:file"></tri-icon>
    <tri-icon svgIcon="twotone:file-unknown"></tri-icon>
    <tri-icon svgIcon="twotone:file-word"></tri-icon>
    <tri-icon svgIcon="twotone:file-zip"></tri-icon>
    <tri-icon svgIcon="twotone:filter"></tri-icon>
    <tri-icon svgIcon="twotone:fire"></tri-icon>
    <tri-icon svgIcon="twotone:flag"></tri-icon>
    <tri-icon svgIcon="twotone:folder-add"></tri-icon>
    <tri-icon svgIcon="twotone:folder-open"></tri-icon>
    <tri-icon svgIcon="twotone:folder"></tri-icon>
    <tri-icon svgIcon="twotone:frown"></tri-icon>
    <tri-icon svgIcon="twotone:fund"></tri-icon>
    <tri-icon svgIcon="twotone:funnel-plot"></tri-icon>
    <tri-icon svgIcon="twotone:gift"></tri-icon>
    <tri-icon svgIcon="twotone:gold"></tri-icon>
    <tri-icon svgIcon="twotone:hdd"></tri-icon>
    <tri-icon svgIcon="twotone:heart"></tri-icon>
    <tri-icon svgIcon="twotone:highlight"></tri-icon>
    <tri-icon svgIcon="twotone:home"></tri-icon>
    <tri-icon svgIcon="twotone:hourglass"></tri-icon>
    <tri-icon svgIcon="twotone:html5"></tri-icon>
    <tri-icon svgIcon="twotone:idcard"></tri-icon>
    <tri-icon svgIcon="twotone:info-circle"></tri-icon>
    <tri-icon svgIcon="twotone:insurance"></tri-icon>
    <tri-icon svgIcon="twotone:interaction"></tri-icon>
    <tri-icon svgIcon="twotone:layout"></tri-icon>
    <tri-icon svgIcon="twotone:left-circle"></tri-icon>
    <tri-icon svgIcon="twotone:left-square"></tri-icon>
    <tri-icon svgIcon="twotone:like"></tri-icon>
    <tri-icon svgIcon="twotone:lock"></tri-icon>
    <tri-icon svgIcon="twotone:mail"></tri-icon>
    <tri-icon svgIcon="twotone:medicine-box"></tri-icon>
    <tri-icon svgIcon="twotone:meh"></tri-icon>
    <tri-icon svgIcon="twotone:message"></tri-icon>
    <tri-icon svgIcon="twotone:minus-circle"></tri-icon>
    <tri-icon svgIcon="twotone:minus-square"></tri-icon>
    <tri-icon svgIcon="twotone:mobile"></tri-icon>
    <tri-icon svgIcon="twotone:money-collect"></tri-icon>
    <tri-icon svgIcon="twotone:notification"></tri-icon>
    <tri-icon svgIcon="twotone:pause-circle"></tri-icon>
    <tri-icon svgIcon="twotone:phone"></tri-icon>
    <tri-icon svgIcon="twotone:picture"></tri-icon>
    <tri-icon svgIcon="twotone:pie-chart"></tri-icon>
    <tri-icon svgIcon="twotone:play-circle"></tri-icon>
    <tri-icon svgIcon="twotone:play-square"></tri-icon>
    <tri-icon svgIcon="twotone:plus-circle"></tri-icon>
    <tri-icon svgIcon="twotone:plus-square"></tri-icon>
    <tri-icon svgIcon="twotone:pound-circle"></tri-icon>
    <tri-icon svgIcon="twotone:printer"></tri-icon>
    <tri-icon svgIcon="twotone:profile"></tri-icon>
    <tri-icon svgIcon="twotone:project"></tri-icon>
    <tri-icon svgIcon="twotone:property-safety"></tri-icon>
    <tri-icon svgIcon="twotone:pushpin"></tri-icon>
    <tri-icon svgIcon="twotone:question-circle"></tri-icon>
    <tri-icon svgIcon="twotone:reconciliation"></tri-icon>
    <tri-icon svgIcon="twotone:red-envelope"></tri-icon>
    <tri-icon svgIcon="twotone:rest"></tri-icon>
    <tri-icon svgIcon="twotone:right-circle"></tri-icon>
    <tri-icon svgIcon="twotone:right-square"></tri-icon>
    <tri-icon svgIcon="twotone:rocket"></tri-icon>
    <tri-icon svgIcon="twotone:safety-certificate"></tri-icon>
    <tri-icon svgIcon="twotone:save"></tri-icon>
    <tri-icon svgIcon="twotone:schedule"></tri-icon>
    <tri-icon svgIcon="twotone:security-scan"></tri-icon>
    <tri-icon svgIcon="twotone:setting"></tri-icon>
    <tri-icon svgIcon="twotone:shop"></tri-icon>
    <tri-icon svgIcon="twotone:shopping"></tri-icon>
    <tri-icon svgIcon="twotone:skin"></tri-icon>
    <tri-icon svgIcon="twotone:sliders"></tri-icon>
    <tri-icon svgIcon="twotone:smile"></tri-icon>
    <tri-icon svgIcon="twotone:snippets"></tri-icon>
    <tri-icon svgIcon="twotone:sound"></tri-icon>
    <tri-icon svgIcon="twotone:star"></tri-icon>
    <tri-icon svgIcon="twotone:stop"></tri-icon>
    <tri-icon svgIcon="twotone:switcher"></tri-icon>
    <tri-icon svgIcon="twotone:tablet"></tri-icon>
    <tri-icon svgIcon="twotone:tag"></tri-icon>
    <tri-icon svgIcon="twotone:tags"></tri-icon>
    <tri-icon svgIcon="twotone:thunderbolt"></tri-icon>
    <tri-icon svgIcon="twotone:tool"></tri-icon>
    <tri-icon svgIcon="twotone:trademark-circle"></tri-icon>
    <tri-icon svgIcon="twotone:trophy"></tri-icon>
    <tri-icon svgIcon="twotone:unlock"></tri-icon>
    <tri-icon svgIcon="twotone:up-circle"></tri-icon>
    <tri-icon svgIcon="twotone:up-square"></tri-icon>
    <tri-icon svgIcon="twotone:usb"></tri-icon>
    <tri-icon svgIcon="twotone:video-camera"></tri-icon>
    <tri-icon svgIcon="twotone:wallet"></tri-icon>
    <tri-icon svgIcon="twotone:warning"></tri-icon>

  `,
  styles  : []
})
export class TriDemoIconTwotone {

}
