name: CI
'on':
  - push
jobs:
  bazel_build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node:
          - '12'
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node }}"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: "${{ runner.os }}-yarn-\n"
      - name: Installing project dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Setting up global Bazel binary
        run: "./scripts/circleci/setup_bazel_binary.sh"
      - run: yarn build
      - run: yarn check-release-output
